wandb_version: 1

use_wandb:
  desc: null
  value: true
wandb_project:
  desc: null
  value: cv-project
wandb_group:
  desc: null
  value: mlp
job_type:
  desc: null
  value: training
wandb_name:
  desc: null
  value: ''
user_name:
  desc: null
  value: dl_project_
model:
  desc: null
  value: mlp
dataset_folder:
  desc: null
  value: /home/ubuntu/learning_minimal/5p2v/MODEL
anchors:
  desc: null
  value: 26
seed:
  desc: null
  value: 1
batch_size:
  desc: null
  value: 32
lr:
  desc: null
  value: 0.001
weight_decay:
  desc: null
  value: 0
momentum:
  desc: null
  value: 0.9
num_epoch:
  desc: null
  value: 80
save_interval:
  desc: null
  value: 3
save_dir:
  desc: null
  value: /home/ubuntu/learning_minimal/5p2v/models/mlp
total_updates:
  desc: null
  value: 50000
optimizer:
  desc: null
  value: sgd
_wandb:
  desc: null
  value:
    python_version: 3.8.0
    cli_version: 0.15.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1686816266.677957
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 17
      - 23
      - 37
      4: 3.8.0
      5: 0.15.2
      8:
      - 5
